# Travis CI integration

language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j4 && make test
